/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package projeto_corrida;

public class App {
    public static void main (String[] args){
        App aplicacao = new App ();
        Pessoa p1 = new Pessoa ("Rogerio");
        Piloto pil1 = new Piloto ("Felipe");
        System.out.println(p1.mostrarNome());
        System.out.println(pil1.mostrarNome());
    }
}
